### PR TITLE
Fix browsercount

### PR DESCRIPTION
**Pull request by jerbob92**
The browsercount in closeAll is incorrect.

### CODE REVIEW

**Comment by FWeinb** [comment]
Thanks for doing this PR. Totally missed that one. Is this ready or are you still working on it?

**Comment by jerbob92** [comment]
Ah sorry. I forgot I made a PR for this. I continued to work on this as this just won't work for us in the current form. 

The only relevant change is "this.browserCount = 0;" > "this.count = 0;"

However, I also found out that browsers are not actually closing and thus leaving leftover processes.

**Comment by FWeinb** [comment]
On what OS are you experiencing these issues. I tested it on macOS and it worked fine in the past.

**Comment by jerbob92** [comment]
On Linux (Ubuntu inside a docker container), when I run ```app.quit()```, the actual Electron process never gets closed. When I run ```app.exit(0)``` it does work. I had some major problems with hanging/crashing electrons so now I'm just calling ```screenshot.close();``` (which triggers ```browser.closeAll();```) before I take a screenshot so I always have a fresh browser process. It's a little slower but at least I know I have a working service. 

I run 4 docker containers with a renderer to scale.

**Comment by jerbob92** [comment]
I created a proper PR in #22

**Pull request closed without merging**
